# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('projeto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('obs', models.CharField(max_length=200)),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscatag.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pessoatag',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscatag.Tag'),
        ),
    ]
