# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscatag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoatag',
            old_name='id_pessoa',
            new_name='pessoa',
        ),
        migrations.RenameField(
            model_name='pessoatag',
            old_name='id_tag',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='nometag',
            new_name='nome',
        ),
    ]
