# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscatag', '0002_auto_20170108_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='imagem',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
