# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscatag', '0003_tag_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscatag.Pessoa')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscatag.Tag')),
            ],
        ),
    ]
