# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscatag', '0008_projetolist_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetolist',
            old_name='nome',
            new_name='devs',
        ),
    ]
