# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscatag', '0010_auto_20170112_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetolist',
            name='devs',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='buscatag.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetolist',
            name='tag',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='buscatag.Tag'),
            preserve_default=False,
        ),
    ]
