# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscatag', '0012_auto_20170112_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetolist',
            name='devs',
        ),
        migrations.AddField(
            model_name='projetolist',
            name='devs',
            field=models.ManyToManyField(to='buscatag.Pessoa'),
        ),
    ]
